<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.paypal.orders.OrdersAuthorizeTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2018-08-23T19:19:56" hostname="LM-SJN-21017303" time="0.61">
  <properties/>
  <testcase name="testOrdersAuthorizeRequest" classname="com.paypal.orders.OrdersAuthorizeTest" time="0.61">
    <failure message="com.braintreepayments.http.exceptions.HttpException: {&quot;name&quot;:&quot;INVALID_REQUEST&quot;,&quot;message&quot;:&quot;Request is not well-formed, syntactically incorrect, or violates schema.&quot;,&quot;debug_id&quot;:&quot;d36550fee7860&quot;,&quot;details&quot;:[{&quot;field&quot;:&quot;prefer&quot;,&quot;value&quot;:&quot;ug5Cga6A2Qy2iP9dL74&quot;,&quot;location&quot;:&quot;header&quot;,&quot;issue&quot;:&quot;INVALID_PARAMETER_VALUE&quot;,&quot;description&quot;:&quot;The value of a field is invalid&quot;}],&quot;links&quot;:[{&quot;href&quot;:&quot;developer.paypal.com/docs/api/orders/#INVALID_REQUEST&quot;,&quot;rel&quot;:&quot;information_link&quot;,&quot;encType&quot;:&quot;application/json&quot;}]}" type="com.braintreepayments.http.exceptions.HttpException">com.braintreepayments.http.exceptions.HttpException: {&quot;name&quot;:&quot;INVALID_REQUEST&quot;,&quot;message&quot;:&quot;Request is not well-formed, syntactically incorrect, or violates schema.&quot;,&quot;debug_id&quot;:&quot;d36550fee7860&quot;,&quot;details&quot;:[{&quot;field&quot;:&quot;prefer&quot;,&quot;value&quot;:&quot;ug5Cga6A2Qy2iP9dL74&quot;,&quot;location&quot;:&quot;header&quot;,&quot;issue&quot;:&quot;INVALID_PARAMETER_VALUE&quot;,&quot;description&quot;:&quot;The value of a field is invalid&quot;}],&quot;links&quot;:[{&quot;href&quot;:&quot;developer.paypal.com/docs/api/orders/#INVALID_REQUEST&quot;,&quot;rel&quot;:&quot;information_link&quot;,&quot;encType&quot;:&quot;application/json&quot;}]}
	at com.braintreepayments.http.HttpClient.parseResponse(HttpClient.java:198)
	at com.braintreepayments.http.HttpClient.execute(HttpClient.java:98)
	at com.paypal.orders.OrdersAuthorizeTest.testOrdersAuthorizeRequest(OrdersAuthorizeTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:133)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:83)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:364)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
